server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password: Truong2092004a@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true